[package]

name = "rust-hello-world"
version = "0.0.1"
edition = "2021"
authors = ["Shoaib <shoaib@actonate.com>"]
repository="https://github.com/shoaibmerchant/rust-hello-world"

[dependencies]
bevy = { version = "0.9.1", features = ["wayland"] }
